apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: gateway-service-sa
      containers:
        - name: gateway-service
          image: liorash7/goodsteams-gateway-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rsa-keys
              mountPath: /etc/rsa
      volumes:
        - name: rsa-keys
          secret:
            secretName: rsa-keys-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: liorash7/goodsteams-auth-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rsa-keys
              mountPath: /etc/rsa
      volumes:
        - name: rsa-keys
          secret:
            secretName: rsa-keys-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: liorash7/goodsteams-profile-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rsa-keys
              mountPath: /etc/rsa
      volumes:
        - name: rsa-keys
          secret:
            secretName: rsa-keys-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: liorash7/goodsteams-book-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080