version: '3'

services:
  gateway-service:
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-gateway-service:latest

  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-auth-service:latest

  profile-service:
    build:
      context: ./profileservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-profile-service:latest