version: '3'

services:
  gateway-service:
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-gateway-service:latest

  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-auth-service:latest

  profile-service:
    build:
      context: ./profileservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-profile-service:latest

  book-service:
    build:
      context: ./bookservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-book-service:latest

  order-service:
    build:
      context: ./orderservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-order-service:latest

  library-service:
    build:
      context: ./libraryservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-library-service:latest

  wishlist-service:
    build:
      context: ./wishlistservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-wishlist-service:latest

  review-service:
    build:
      context: ./reviewservice
      dockerfile: Dockerfile
    image: liorash7/goodsteams-review-service:latest
    