apiVersion: v1
kind: Service
metadata:
  name: community-service-service
spec:
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP