apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer