apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "goodsteams-kafka-0.goodsteams-kafka-headless.default.svc.cluster.local:9092,goodsteams-kafka-1.goodsteams-kafka-headless.default.svc.cluster.local:9092,goodsteams-kafka-2.goodsteams-kafka-headless.default.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 31000
  selector:
    app: kafdrop