apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: liorash7/goodsteams-profile-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rsa-keys
              mountPath: /etc/rsa
      volumes:
        - name: rsa-keys
          secret:
            secretName: rsa-keys-secret