apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-service-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: gateway-service-sa
    namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io